// SYNTAX

// this is a single-line comment!

/*this is a...
multi-line comment

- What you downloaded was actually three things:
  - scide, sclang/interpreter (client), scsynth (server)
- [Client vs Server](https://doc.sccode.org/Guides/ClientVsServer.html)
- OSC messages between Client and Server
- IDE: Text Editor, Post window, Help browser
- Client (Interpreter/Language) boots when you open IDE
- You do need to ACTIVELY boot scsynth/audio server with **Command|B** (or with drop-down or with s.boot)
- You see your hardware I/O in the Post window after booting the Audio Server
- [You might need to change them/select them with this code](https://doc.sccode.org/Reference/AudioDeviceSelection.html)
- If you I/O audio rates don't match, the server won't boot and you'll need to make sure they match in your Audio MIDI setup
- Evaluate a line with **Shift|Return**
- Evaluate a block with **Command|Return**
- Kill the busses going to the server with **Command|.**
- You can run server(s) from anything/anywhere
- ***Beware Zombie servers***
- Everything's in mono by default
- "Syntax Sugar": many ways to write out the same thing
- Help! with **Command|D**
*/

// objects and messages
// We can assign objects to variables, and then send messages to those objects with the syntax `object.message.` messages will be received (and sent) based on an object's methods

~breakfast = { "eggs".scramble };
~breakfast.value;

// ~variables are environment variables
~massimo={"SuperCollider loves Massimo".postln};
~massimo.value; // .value is another

// SC has operator precedence, but it’s safer to parenthesize aggressively
(
"I love SuperCollider".postln;
"SuperCollider loves me".postln;
)

(100+2/2).postln; // what does this equal?
(100+(2/2)).postln; // force order of operations using parentheses

// conditionals!
// if
if(2 + 2 == 4, { "Nice" }, { "What" }).postln;

// case
(
x = 1002;

case
{ x < 0 }      { "It's negative".postln; }
{ x > 1000 }   { "It's nonnegative, but too big".postln; }
{ x % 2 == 0 } { "It's an even number".postln; }
{ true }       { "It's an odd number".postln; };
)

// FUNCTIONS & PARAMETERS

/*
Arguments live on the SERVER.
Variables live on the CLIENT.

You can change arguments on the fly.
Changing variables requires re-executing the function.
*/

// variables need to be declared but not by their type (which is good AND bad...)
// local variables are hella local:
a = 1;
(
var a;
a = 3;
);
a;

// a template function definition with both an argument and a local variable
(
~banana={ // CURLY BRACKETS WRAP FUNCTIONS
	| urname = "rachel" | // arguments must be defined first within the function
	var x; // then variables must be defined next
	x="bleeePPP BLLLooooopS"; // variables can be assigned later
	(urname++", do you want to make "++x++"?").postln;
};
);
~banana.value;
~banana.("rooommmmee");

// arguments can be passed into functions when the function has already been passed to the server
/* can be called two ways:
arg ;//old-school "pirate" notation
| | //"pipe notation"
*/

/*
// server methods
- 's' stands for server! Don't assign things to it
- useful **s.** commands*/
 s.makeWindow;
 s.meter;
 s.record;
 s.stopRecording;
 s.scope; // time domain!!!
 s.freqscope; // frequency domain!!!

/* UGens
- Modular building blocks of SuperCollider Systems for synthesis; sound design; algorithmic composition
- In SC they're actually written in C/C++ and are a plugin to the SC Audio Server, but most come standard with download
- Most UGen classes have Audio Rate **.ar** and Control Rate **.kr** signal methods internal to the language
- AR = sends 44.1k values per second; KR = sends 7,350 values per second (1/6th as many as ar. Just saves CPU this way!...like difference between VCO and LFO modules in an analog modular synthesizer).
- LOOK UP THE arguments OF UGens with <<Command|D>> ALL THE TIME
- SinOsc is the "hello, world" of computer music.
- Look at Mul and Add methods of SinOsc in its help file
https://doc.sccode.org/Guides/Tour_of_UGens.html
- your early SC use will be weaving parameters of UGens together; using OOP to swap related methods
*/

(
~orange={
	arg pitch=166; /* PIRATE vs PIPE NOTATION a la rachelle */
	// | pitch=220 |
	SinOsc.ar(pitch);
}.play; // .play will play it
)
~orange.set(\pitch,455);
~orange.set(\pitch,51.midicps); // .midicps converts midi note to frequency (cycles per second)
~orange.free; // we can stop the play functions with this line

/*Stopping sounds with sophistication*
.free - kills bus assigned to variable on the server (ideal)
<<Command|.>> - kills all busses on the server (panic)
Server>Kill All Servers > KILLS ALL SERVERS (apocalypse)

Let's get out of mono with Pan2:*/
(
~kiwi={
	| pitch=220, pan=1 | // N.B. only arguments in this function, no local variables
	Pan2.ar(SinOsc.ar(pitch), SinOsc.kr(pan)); // .kr vs .ar!
}.play; // .play will play it
)
~kiwi.set(\pitch,440)
~kiwi.set(\pan, 4)
~kiwi.free;

//Why the pop sound? because the phase is interrupted. We don't have envelopes yet!

/*
UGens you should know for output, read help files for all!
Pan2 // Rachel Recommends for Stereo Field
Out // For sending signals directly to the bus that goes to your hardware Output Device ("master")
Mix // Great for simple submixing, adding a bunch of channels together
Splay // Great for complex submixing, spreading a bunch of channels across the Stereo Field
PanAz // Multi-channel panning gold!
*/